### ISSUE TITLE
Error in matlab 2016

### ISSUE THREAD

**Issue by Bragadeeshan** [dnjayasinghe/MLResearch#3]
Attempt to execute SCRIPT strings as a function:
C:\Program Files\MATLAB\R2016a\toolbox\matlab\strfun\strings.m

Error in CPAPlot (line 95)
        PtFileStr = strings([NUM_ENC, 16]);

**Comment by dnjayasinghe** [comment]
I fixed this error in the new push and https://github.com/dnjayasinghe/MLResearch/tree/Matlab-Command-Check branch. Could you check, please?

**Comment by dnjayasinghe** [comment]
Fixed the error and tested using matlab 2011
